### ISSUE TITLE
Pas d'échange possible avec le speaker dans le cfp

### ISSUE THREAD

**Issue by jefBinomed** [SII-Nantes/callForPaper#1]
Quand on est dans la partie admin, les commentaires ne sont dispo que pour les admin et pas pour le speaker. C'est dommage, ça aurait permis une interaction avec le speaker. genre questions réponses

**Comment by Thom-x** [comment]
Je peux mettre ça en place, après je sais pas si vous voulez que les commentaires restent privés ou non (pour pouvoir clasher les speakers :p)

**Comment by jefBinomed** [comment]
tu clos, on laisse tel quel du coup :)

Le jeu. 4 juin 2015 à 16:13, MAUGIN Thomas <notifications@github.com> a
écrit :

> Je peux mettre ça en place, après je sais pas si vous voulez que les
> commentaires restent privés ou non (pour pouvoir clasher les speakers :p)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SII-Nantes/callForPaper/issues/1#issuecomment-108910707>
> .
>
-- 
-----------------------------------------------------------------------
Jean-François Garreau - Binomed - GDG Nantes
Tel : +336.48.28.15.28
Email perso: jean.francois.garreau@gmail.com
Email pro: jean.francois.garreau@binomed.fr
Site Web: http://jef.binomed.fr | http://gdgnantes.com
Follow me: @jefBinomed +JeanFrancoisGarreau
