### ISSUE TITLE
Modification texte

### ISSUE THREAD

**Issue by xavmarc** [SII-Nantes/callForPaper#10]
Dans l'étape 2 : 
- Supprimer la phrase suivante : Discovery est une catégorie pour les conférences non techniques.

Dans l'étape 3 :
- Changer le texte d'intro par : Vous pouvez renseigner içi les informations nécessaires pour votre venue. Ces informations seront minutieusement étudiées pour notre décision. Ne choisissez oui que si vous en avez besoin. Un petit déjeuner et un déjeuner sont offerts le jour de l'évènement.

**Comment by jlandure** [comment]
+ email 
Confirmation de votre session
Bonjour Julien,
Votre session Essai1 a bien été enregistrée. Nous reviendrons vers vous dès que nous aurons la sélections des sessions.
=> sélection sans S !!! :100: 

Bonus : ajouter un lien vers le talk Essai1 !
