### ISSUE TITLE
etape 3 typo ici au lieu de içi et l’événement au lieu de l'évènement

### ISSUE THREAD

**Issue by vp-pguyard** [SII-Nantes/callForPaper#13]
Vous pouvez renseigner içi les informations nécessaires pour votre venue. Ces informations seront minutieusement étudiées pour notre décision. Ne choisissez oui que si vous en avez besoin.

Un petit déjeuner et un déjeuner sont offerts le jour de l’événement.

**Comment by Thom-x** [comment]
Tsss ça c'est de la faute a @xavmarc j'ai fais un copier collé (#10)...

**Comment by pguyard** [comment]
bouh @xavmarc :p

**Comment by jlandure** [comment]
évènement et événement, les 2 se disent mais c'est mieux "évènement" :+1:

**Comment by Thom-x** [comment]
http://fr.wikipedia.org/wiki/%C3%89v%C3%A9nement

**Comment by jlandure** [comment]
oui c'est bien ça. Il vaut mieux écrire "évènement".
```
l'Académie française a adopté la graphie évènement, mais estime que « la graphie ancienne événement n'est cependant pas considérée comme fautive, encore que rien ne la justifie plus ».
...
Cependant, la graphie « évènement » peut paraître plus envisageable, car un accent grave sur la lettre « e » se place quand cette dernière est suivie d'une syllabe dont la dernière lettre est un « e muet », comme c'est le cas ici.
```

**Comment by Thom-x** [comment]
Je remets la bonne orthographe, je pensais avoir changé "é" par "è" mais non.
