### ISSUE TITLE
étape 2 - impossible de passer à l'étape 3

### ISSUE THREAD

**Issue by pguyard** [SII-Nantes/callForPaper#14]
lorsque j'arrive sur l'étape je tente direct de passer à l'étape 3, j'ai bien les erreurs de validation, je complète et la je peux pas aller à l'étape 3 (revalidation ko)

**Comment by Thom-x** [comment]
As-tu bien mis la difficulté ? (elle ne passe pas en rouge à la validation).

**Comment by vp-pguyard** [comment]
effectivement c'est la difficulté qui manque !

**Comment by Thom-x** [comment]
Je regarderai ça demain, c'est un plugin angular qui prend pas en compte la validation.
