### ISSUE TITLE
Ajouter le titre du talk pour le dashboard (brouillon + talk validé)

### ISSUE THREAD

**Issue by jlandure** [SII-Nantes/callForPaper#18]
on voit uniquement 
"Brouillon modifié le 22/06/2015, 11:10:08" mais on sait quel talk c'est !
Faudrait indiquer le titre du talk.

**Comment by Thom-x** [comment]
Je peux rajouter le titre, mais on est pas obligé de le mettre donc il ne sera pas toujours là.

**Comment by jlandure** [comment]
le titre est obligatoire... donc je ne vois pas le usecase! tu peux détailler ?

**Comment by Thom-x** [comment]
En brouillon tu peux sauvegarder à tout moment pas besoin de remplir les champs.

**Comment by jlandure** [comment]
L'idéal serait de forcer à mettre au moins un titre (même en mode brouillon)...

**Comment by Thom-x** [comment]
Le titre est à l'étape n°2 ce qui veut dire qu'il faut obligatoirement finir l'étape n°1 avant, c'est un peu contraignant pour l'utilisateur et c'est plus trop brouillon :/

Au pire on laisse comme j'ai fais, on affiche le titre seulement s'il a été renseigné sinon on met juste la date.
