### ISSUE TITLE
Pouvoir distinguer les liens de l'utilisateur

### ISSUE THREAD

**Issue by jlandure** [SII-Nantes/callForPaper#20]
aujourd'hui tout est en vrac dans "URL" mais on pourrait prévoir des champs dédiés : 
* github
* googleplus
* twitter
* site web
Il faudrait faire en sorte que cela soit "cliquable" dans la vue admin...

**Comment by Thom-x** [comment]
Je peux mettre ça en place, par contre, les anciennes données serons pas forcément dans les bons champs.
Je sais pas si tu as vu, mais le champ pour entrer les liens est pas classique, mais un "tag input".

**Comment by jlandure** [comment]
Niveau champ, je parlais côté admin et c'est pas terrible :)
Pour l'ancien champ, no pb, ça veut juste dire que les nouveaux pourront renseigner comme il faut leur github, gplus et twitter mais on laissera tjs le champs url comme il est aujourd'hui.

**Comment by Thom-x** [comment]
Ok, je vais mettre ça un peu plus clair côté admin alors.

**Comment by Thom-x** [comment]
ATTENTION

Le commit a été fait 2adc684c41b441f80dff27fae2c169d5bb7767a9,
Il faut bien s'assurer que les champs "twitter", "googlePlus" et "github" sont bien ajouté à la fin de la spreadsheet (ils sont normalement ajoutés au (re)lancement de l'appli).

![capture](https://cloud.githubusercontent.com/assets/6797195/8620684/7356a9ee-2721-11e5-8a9f-0692d877d534.PNG)

**Comment by jlandure** [comment]
Que veux-tu dire par "relancement de l'appli" ?

**Comment by Thom-x** [comment]
Après le déploiement sur appengine à la première requête.

**Comment by jlandure** [comment]
zarb, on l'a pas dans l'ihm ni dans le fichier excel... il nous manque p'etre un truc...
on verra ça semaine pro

**Comment by Thom-x** [comment]
C'est normal tu as pas mergé ce commit, je l'ai fais aujourd'hui.

**Comment by jlandure** [comment]
j'ai bien les colonnes now :+1:

**Comment by Thom-x** [comment]
Je peux close ?

**Comment by jlandure** [comment]
j'ai pas vérifié mais oui ^^
