### ISSUE TITLE
Avoir le nb total de talks déposés (en cours et validés)

### ISSUE THREAD

**Issue by jlandure** [SII-Nantes/callForPaper#21]
et aussi avoir le nb total de speakers.

Mettre ces compteurs en haut à gauche dans la partie admin entre le bandeau "Administration" et le tableau. (même niveau que le bouton de droite "annuler le tri")

**Comment by Thom-x** [comment]
Pour toi c'est quoi "en cours" et "validé" ?

**Comment by jlandure** [comment]
enfin je veux dire : brouillon et validé. c'est ça les termes utilisés non ?

**Comment by Thom-x** [comment]
Ok, j'ai fais les validés, demain je fais l'autre.
Le 29 juin 2015 6:01 PM, "Julien Landuré" <notifications@github.com> a
écrit :

**Comment by jlandure** [comment]
Salut,

Je pense qu'il faut réouvrir le ticket.
Deux remarques
* les icônes ne sont pas très parlantes ("validé" avec l'icone "commentaire" et le "brouillon" avec l'image "insert-drive"). Mettre au moins un alt pour avoir du texte en surbrillance pour expliquer l'icône.
* les compteurs sont faux pour les talks car le compteur des "validés" prend en compte la pagination. Si je clique sur 10, j'ai 10 talks... si je clique sur 25, j'ai bien 22 talks :)
