### ISSUE TITLE
Tes urls ne sont pas RESTful

### ISSUE THREAD

**Issue by jlandure** [SII-Nantes/callForPaper#24]
* sessions pour avoir toutes les sessions 
* session/ID pour avoir une session

Dans l'idée, il faut avoir 
* `GET /sessions` pour avoir toutes les sessions
* `GET /sessions/ID` pour avoir une session particulière !
D'ailleurs, le terme "session" est bizarre. session = talk c'est bien ça ? :) 

cf http://stackoverflow.com/a/21809963

**Comment by Thom-x** [comment]
OK.

>D'ailleurs, le terme "session" est bizarre. session = talk c'est bien ça ? :)

Oui, mais talk n'est pas mieux étant donné qu'il y a aussi des codelabs.
http://www.wordreference.com/enfr/session
