### ISSUE TITLE
Pourquoi la délibération est dans "Aide financière" ?

### ISSUE THREAD

**Issue by jlandure** [SII-Nantes/callForPaper#25]
Je trouve le nom de l'onglet étonnant :)
Peut-être mettre plutôt l'aide financière et la délibération dans un autre onglet 'votes' ?

**Comment by Thom-x** [comment]
La "délibération" est en dessous des 3 onglets (pas dans le dernier), je l'ai mis comme ça pour toujours avoir un œil sur le fil de la discussion.
Si tu veux je peux mieux séparer visuellement les onglets et la "délibérations" ? 

Je veux bien changer le titre "aide financière", j'étais pas trop inspiré, une idée ?
