### ISSUE TITLE
Pouvoir uploader une photo pour les speakers

### ISSUE THREAD

**Issue by jlandure** [SII-Nantes/callForPaper#28]
Ca serait intéressant de pouvoir ajouter une fonction pour uploader son avatar ?
On serait sur des images 140x140.
L'idéal serait de proposer par défaut de récupérer l'image avec la connexion googleplus ou github puis de proposer de changer d'image si besoin en uploadant une nouvelle image.

PS : regarde du coté de l'API blobstore d'appengine :+1:

**Comment by jefBinomed** [comment]
rectification 360x360 ;)

Le mer. 8 juil. 2015 à 09:30, Julien Landuré <notifications@github.com> a
écrit :

> Ca serait intéressant de pouvoir ajouter une fonction pour uploader son
> avatar ?
> On serait sur des images 140x140.
> L'idéal serait de proposer par défaut de récupérer l'image avec la
> connexion googleplus ou github puis de proposer de changer d'image si
> besoin en uploadant une nouvelle image.
>
> PS : regarde du coté de l'API blobstore d'appengine [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SII-Nantes/callForPaper/issues/28>.
>
-- 
-----------------------------------------------------------------------
Jean-François Garreau - Binomed - GDG Nantes
Tel : +336.48.28.15.28
Email perso: jean.francois.garreau@gmail.com
Email pro: jean.francois.garreau@binomed.fr
Site Web: http://jef.binomed.fr | http://gdgnantes.com
Follow me: @jefBinomed +JeanFrancoisGarreau
