### ISSUE TITLE
Dans la partie speaker, on ne peut pas éditer ses informations

### ISSUE THREAD

**Issue by jefBinomed** [SII-Nantes/callForPaper#3]
On ne peut rien éditer. Ni les informations du speaker, ni les informations du talk :(

Faudrait pouvoir éditer ça car du coup, on est obligé de tout bien écrire dès la première fois

**Comment by Thom-x** [comment]
Normalement tu enregistres en brouillon tant que tu veux pas poster un talk et quand tout est OK tu peux le poster. Après je sais pas si vous voulez qu'on puisse modifier même une fois posté (peut être seulement certain champs) ?

**Comment by jefBinomed** [comment]
Oui c'est ça, ça serait mieux de pouvoir éditer après, même après la
soumission

Le jeu. 4 juin 2015 13:38, MAUGIN Thomas <notifications@github.com> a
écrit :

> Normalement tu enregistres en brouillon tant que tu veux pas poster un
> talk et quand tout est OK tu peux le poster. Après je sais pas si vous
> voulez qu'on puisse modifier même une fois posté (peut être seulement
> certain champs) ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SII-Nantes/callForPaper/issues/3#issuecomment-108853748>
> .
>
-- 
-----------------------------------------------------------------------
Jean-François Garreau - Binomed - GDG Nantes
Tel : +336.48.28.15.28
Email perso: jean.francois.garreau@gmail.com
Email pro: jean.francois.garreau@binomed.fr
Site Web: http://jef.binomed.fr | http://gdgnantes.com
Follow me: @jefBinomed +JeanFrancoisGarreau
