### ISSUE TITLE
Côté admin, pouvoir modifier son vote

### ISSUE THREAD

**Issue by jlandure** [SII-Nantes/callForPaper#30]
Des fois en relisant d'autres talks, on peut être amener à changer son jugement :)
Il faudrait pouvoir éditer son vote (1 à 5)

**Comment by jefBinomed** [comment]
c'est le cas déjà ?

Le ven. 10 juil. 2015 à 12:09, Julien Landuré <notifications@github.com> a
écrit :

> Des fois en relisant d'autres talks, on peut être amener à changer son
> jugement :)
> Il faudrait pouvoir éditer son vote (1 à 5)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SII-Nantes/callForPaper/issues/30>.
>
-- 
-----------------------------------------------------------------------
Jean-François Garreau - Binomed - GDG Nantes
Tel : +336.48.28.15.28
Email perso: jean.francois.garreau@gmail.com
Email pro: jean.francois.garreau@binomed.fr
Site Web: http://jef.binomed.fr | http://gdgnantes.com
Follow me: @jefBinomed +JeanFrancoisGarreau

**Comment by Thom-x** [comment]
> c'est le cas déjà ?

Oui

**Comment by jlandure** [comment]
ah ! j'ai pas compris ou c'était !
C'est pas sur mon vote qu'il faut changer mais il faut faire comme si on ajoutait un vote !
_pas terrible niveau UX_ mais bon ça marche !

idée : on pourrait enlever dans la liste des votes, son vote puisqu'on le voit en haut en gardant l'image de la personne qui vote ?
(merger les 2 items du haut en fait ^^)

![votes_ux](https://cloud.githubusercontent.com/assets/525974/8617960/7369bcd6-2709-11e5-9090-a22892dd86b6.png)

**Comment by jlandure** [comment]
il faudrait aussi mettre la moyenne en haut et pas en bas des votes.
Plus il y a de votants plus il faut descendre pour le voir...
On pourrait même le remettre avec une icône en haut à côté de "supprimer le vote". Qu'en pensez-vous ?

**Comment by jefBinomed** [comment]
+1 pour le supprimer le vote )

Le ven. 10 juil. 2015 à 13:43, Julien Landuré <notifications@github.com> a
écrit :

> il faudrait aussi mettre la moyenne en haut et pas en bas des votes.
> Plus il y a de votants plus il faut descendre pour le voir...
> On pourrait même le remettre avec une icône en haut à côté de "supprimer
> le vote". Qu'en pensez-vous ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SII-Nantes/callForPaper/issues/30#issuecomment-120392940>
> .
>
-- 
-----------------------------------------------------------------------
Jean-François Garreau - Binomed - GDG Nantes
Tel : +336.48.28.15.28
Email perso: jean.francois.garreau@gmail.com
Email pro: jean.francois.garreau@binomed.fr
Site Web: http://jef.binomed.fr | http://gdgnantes.com
Follow me: @jefBinomed +JeanFrancoisGarreau

**Comment by Thom-x** [comment]
Je peut mettre la suppression, mais normalement va y avoir le "sans avis" qui va arriver, je sais pas si ça vaut la peine alors.

**Comment by jlandure** [comment]
Ouhla ! alors on doit pas se comprendre.
Je vais faire un schema ^^

**Comment by jlandure** [comment]
![vote_new](https://cloud.githubusercontent.com/assets/525974/8618130/6ff01be8-270b-11e5-91d9-000be38b5489.png)

**Comment by Thom-x** [comment]
Ça j'ai compris.

**Comment by jlandure** [comment]
![moyenne_en_haut](https://cloud.githubusercontent.com/assets/525974/8618147/a65eb112-270b-11e5-9e51-f3f7285bcb5f.png)

**Comment by Thom-x** [comment]
![capture](https://cloud.githubusercontent.com/assets/6797195/8618253/8ff456ec-270c-11e5-89e5-67a9684569cd.PNG)

**Comment by jefBinomed** [comment]
J'aimerais le garder car des fois on a pas envie de voter mais on veut
savoir qu'on a pris en compte le vote

Le ven. 10 juil. 2015 à 14:04, MAUGIN Thomas <notifications@github.com> a
écrit :

> [image: capture]
> <https://cloud.githubusercontent.com/assets/6797195/8618253/8ff456ec-270c-11e5-89e5-67a9684569cd.PNG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SII-Nantes/callForPaper/issues/30#issuecomment-120395675>
> .
>
-- 
-----------------------------------------------------------------------
Jean-François Garreau - Binomed - GDG Nantes
Tel : +336.48.28.15.28
Email perso: jean.francois.garreau@gmail.com
Email pro: jean.francois.garreau@binomed.fr
Site Web: http://jef.binomed.fr | http://gdgnantes.com
Follow me: @jefBinomed +JeanFrancoisGarreau

**Comment by Thom-x** [comment]
Je voulais dire ajouter un bouton "Supprimer"  ?

**Comment by jefBinomed** [comment]
ah ! Euh @ju ?

Le ven. 10 juil. 2015 à 14:20, MAUGIN Thomas <notifications@github.com> a
écrit :

> Je voulais dire ajouter un bouton "Supprimer" ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SII-Nantes/callForPaper/issues/30#issuecomment-120398176>
> .
>
-- 
-----------------------------------------------------------------------
Jean-François Garreau - Binomed - GDG Nantes
Tel : +336.48.28.15.28
Email perso: jean.francois.garreau@gmail.com
Email pro: jean.francois.garreau@binomed.fr
Site Web: http://jef.binomed.fr | http://gdgnantes.com
Follow me: @jefBinomed +JeanFrancoisGarreau

**Comment by jlandure** [comment]
@jefBinomed je comprend pas du tout ta notion de "j'ai voté" mais à vide...
tu peux expliquer ?

**Comment by jlandure** [comment]
c'est quoi le bouton "supprimer" ? je vous suis plus du tout...

**Comment by Thom-x** [comment]
En faite @jef a lu "supprimer le vote" mais tu voulais dire "supprimer session"
Donc maintenant ya un vieux quiproquo.

**Comment by jefBinomed** [comment]
donc au final pas de bouton "supprimer le vote" et on vire la notion de vote "sans avis", on force le vote un point c'est tout

**Comment by Thom-x** [comment]
Sniff, je trouvais ça pas trop mal pourtant.
Je fais ça dès que j'ai fini les autres issues.

**Comment by jlandure** [comment]
si tu as fini de le développer, laisse-le hein ^^

Le ven. 10 juil. 2015 à 15:25, MAUGIN Thomas <notifications@github.com> a
écrit :

**Comment by Thom-x** [comment]
J'ai finis, c'est commité même.

**Comment by jlandure** [comment]
bah laisse-le alors ^^

Le ven. 10 juil. 2015 à 15:30, MAUGIN Thomas <notifications@github.com> a
écrit :

**Comment by Thom-x** [comment]
fixé 7c475837186388078f1de39ee14d76ff6c8ffe2b
(pas vraiment en rapport avec l'issue de base)
