### ISSUE TITLE
Côté admin, ajouter des flèches pour aller au talk précédent, suivant.

### ISSUE THREAD

**Issue by jlandure** [SII-Nantes/callForPaper#32]
cf image:

![prec_suiv](https://cloud.githubusercontent.com/assets/525974/8620738/cfd59d10-2721-11e5-96df-9c3c907f54fc.png)

**Comment by jefBinomed** [comment]
+1000

Le ven. 10 juil. 2015 à 16:36, Julien Landuré <notifications@github.com> a
écrit :

> cf image:
>
> [image: prec_suiv]
> <https://cloud.githubusercontent.com/assets/525974/8620738/cfd59d10-2721-11e5-96df-9c3c907f54fc.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SII-Nantes/callForPaper/issues/32>.
>
-- 
-----------------------------------------------------------------------
Jean-François Garreau - Binomed - GDG Nantes
Tel : +336.48.28.15.28
Email perso: jean.francois.garreau@gmail.com
Email pro: jean.francois.garreau@binomed.fr
Site Web: http://jef.binomed.fr | http://gdgnantes.com
Follow me: @jefBinomed +JeanFrancoisGarreau

**Comment by Thom-x** [comment]
![capture](https://cloud.githubusercontent.com/assets/6797195/8622014/2df295e0-2729-11e5-9b15-fe6490c95eb7.PNG)

**Comment by jlandure** [comment]
lol :palm_tree:
