### ISSUE TITLE
[ADMIN] Conserver le filtre en place

### ISSUE THREAD

**Issue by jlandure** [SII-Nantes/callForPaper#36]
Quand on filtre les données, qu'on va sur un talk et qu'on go 'back' ou qu'on utilise le bouton "Talks", on perd le filtre en place et la pagination.
Il serait intéressant de garder les paramètres... dans le localstorage par exemple.

**Comment by Thom-x** [comment]
fix 21604075d1a44ca75a6e31945b21b55118892a62
