### ISSUE TITLE
Alignements dans les boutons sur Firefox

### ISSUE THREAD

**Issue by Swiip** [SII-Nantes/callForPaper#39]
Il y a un problème d'alignement des icones des boutons sous Firefox Developer Edition 41.0a2 (2015-07-14)

Voici un exemple de la page d'édition de profile mais c'est le cas pour tous les boutons :
<img width="294" alt="capture d ecran 2015-07-16 a 13 52 24" src="https://cloud.githubusercontent.com/assets/475895/8722180/1ff3f6e4-2bc2-11e5-90e6-0f859d896789.png">

**Comment by jlandure** [comment]
:+1: 
je fais les presentations!
@Thom-x : swiip est un zenika... pointilleux :)

**Comment by Thom-x** [comment]
Même bug qu'au début, je vais regarder ça.

**Comment by jlandure** [comment]
j'ai pas compris tes modifs dans le code ^^ 
tu peux expliquer ?

**Comment by Thom-x** [comment]
Il faut mettre l'élément en float:left/right avant le texte (ce que je ne faisais pas).

cf : http://stackoverflow.com/questions/14416563/bootstrap-use-pull-right-without-having-to-hardcode-a-negative-margin-top
