### ISSUE TITLE
Lenteur de l'application sur le retour sur la liste depuis un talk

### ISSUE THREAD

**Issue by jlandure** [SII-Nantes/callForPaper#41]
J'ai l'impression qu'il recalcule tous les compteurs etc.
Tu peux mettre en place un pti cache (côté front?) pour garder les compteurs à jour et les reloader que tous les 5 min ?
Qu'en penses-tu ?

**Comment by Thom-x** [comment]
Ouais je vais faire ça, je m'en rend pas trop compte vu que je suis en local, mais je viens de tester sur le site et c'est effectivement assez lent.

**Comment by jlandure** [comment]
Je viens de regarder un truc.
Pourquoi fais-tu l'appel à `http://cfp2015.gdgnantes.com/api/admin/draft` ? uniquement pour récupérer un compteur ? tu devrais appeler les compteurs une fois toutes les 5 minutes
style : 
```json
compteurs: {
  speaker: 19,
  draft: 8,
  talks: 12
}
```

**Comment by Thom-x** [comment]
Je sais pas si le plus lent c'est les compteurs ou bien aller chercher dans la Spreadsheet.
En tout cas, je vais faire un compteur à part.

**Comment by Thom-x** [comment]
C'est aller chercher les talks qui prend beauuuuucoup de temps :

![capture](https://cloud.githubusercontent.com/assets/6797195/8722755/069ca406-2bc8-11e5-8326-9272cfcabde8.PNG)

**Comment by jlandure** [comment]
tu peux pas mettre un pti Cache AppEngine (expiration de 5 min) pour la récup des talks ?
=> https://cloud.google.com/appengine/docs/java/memcache/

**Comment by Thom-x** [comment]
Parfait, merci !

**Comment by Thom-x** [comment]
L'affichage du nombre de message nu lu a été mis en cache, ce qui a pour effet de donner exactement la même information à tous les utilisateurs.

**Comment by jlandure** [comment]
quoi ?

**Comment by Thom-x** [comment]
Les propriétés "reviewed" et "nombre de messages non lus" ont été mis en cache.
Si par exemple je me connecte en premier et que j'ai 1 message non lu alors quand tu te connecteras tu auras pareil, alors que pour toi ça pourrait être autre chose.

**Comment by jlandure** [comment]
Heuu alors c'est pas bon. Il faut corriger cela.
Le cache : c'est pour empecher de faire des appels constamment au spreadsheet non ?
Les compteurs : tu peux les calculer à la volée et faire un json comme j'ai indiqué non ?

**Comment by Thom-x** [comment]
>Heuu alors c'est pas bon. Il faut corriger cela.

Oui c'est à corriger, pour ça que j'ai réouvert.
> Le cache : c'est pour empecher de faire des appels constamment au spreadsheet non ?

Oui, je viens de corriger

> Les compteurs : tu peux les calculer à la volée et faire un json comme j'ai indiqué non ?

C'est déjà fait 69ad01b322769c1cf5577c7a82f522bc97a7e982

**Comment by jlandure** [comment]
si c'est déjà fait avec 69ad01b, pourquoi tu dis 
> L'affichage du nombre de message non lu a été mis en cache, ce qui a pour effet de donner exactement la même information à tous les utilisateurs.

**Comment by Thom-x** [comment]
Ok, on parle pas du même compteur, celui qui est mis en cache alors qu'il ne faut pas c'est :

![capture2](https://cloud.githubusercontent.com/assets/6797195/8743433/253d771c-2c6f-11e5-9c6a-b704bdcd9e93.PNG)
(le vert et la dernière colonne)

Et celui qui est bon c'est :

![capture](https://cloud.githubusercontent.com/assets/6797195/8743449/4dc91092-2c6f-11e5-90e6-615b34967f8e.PNG)

**Comment by jlandure** [comment]
Juste pour être sûr, les commentaires et le compteur de commentaire est stockée dans le datastore ? pas dans le spreadsheet ?
rappel : spreadsheet = données talk/speaker uniquement (pas d'infos sur les votes ou les commentaires)

**Comment by Thom-x** [comment]
>Juste pour être sûr, les commentaires et le compteur de commentaire est stockée dans le datastore ? pas dans le spreadsheet ?

Les commentaires dans le Datastore et le(s) compteur(s) généré(s) à la volée.

**Comment by jlandure** [comment]
ok

**Comment by Thom-x** [comment]
TL;DR

J'ai tous mis dans le cache comme un sac alors qu'il fallait pas.

**Comment by Thom-x** [comment]
fixed 89024156b1b127f91c320884fc5ef6793c529e85
