### ISSUE TITLE
[ADMIN] Appel à l'api en double

### ISSUE THREAD

**Issue by jlandure** [SII-Nantes/callForPaper#42]
Quand on va sur l'admin, je vois 2 appels à 
`http://cfp2015.gdgnantes.com/api/adminUser/currentUser`.
C'est pas normal si ?

**Comment by Thom-x** [comment]
Il est appelé une fois quand tu ouvre le site `authService.init()`.
Il est appelé dès que tu change de page dans la partie admin `authService.isAutorizedAdmin`.
Il est aussi appelé dans `session.js`  pour obtenir l'email (gravatar).

**Comment by jlandure** [comment]
c'est donc appellé "beaucoup trop souvent" non ?

**Comment by Thom-x** [comment]
- `authService.init()` est obligatoire pour connaître l'état initial (liens de déco/co).
- `authService.isAutorizedAdmin` pour s'assurer que la personne peut avoir accès à la page (en cas de déconnexion).
- Je pense pouvoir enlever le dernier par contre.
