### ISSUE TITLE
[ADMIN] Ajouter une colonne "Votes"

### ISSUE THREAD

**Issue by jlandure** [SII-Nantes/callForPaper#43]
Ça serait sympa de pouvoir avoir le nombre de votes en filtre.

Le petit plus serait d'avoir une colonne avec les votants.
_Je m'explique:_
* Colonne : Votes
* Filtres : nb de votes croissants / décroissants
* Affichage : icone des avatars des votants en petit (20x20) les uns à la suite des autres toujours ordonnés de la même façon avec un tooltip sur le nom du votant.

cf ci-dessous
![votes](https://cloud.githubusercontent.com/assets/525974/8743786/38b7de6a-2c72-11e5-9d06-94fa9ac4c43a.png)

**Comment by Thom-x** [comment]
Vous allez être combien à voter maximum ?

**Comment by jlandure** [comment]
on ne sait pas à l'avance: tu vas être obligé de faire du float:left ;)
Je te donne quand même une indication : entre 1 et 10 :sweat_smile:

**Comment by Thom-x** [comment]
Voila un aperçu :

![capture](https://cloud.githubusercontent.com/assets/6797195/8746978/da67bb38-2c8e-11e5-91c7-23e4172c67b1.PNG)

**Comment by jlandure** [comment]
ca me parait bien... à voir avec une dizaine de votes ce que ça rend :)

**Comment by Thom-x** [comment]
![capture](https://cloud.githubusercontent.com/assets/6797195/8747146/8cc092d6-2c90-11e5-8e17-642e0961c169.PNG)

**Comment by jlandure** [comment]
vu la capture, je me demandais aussi comment sont géré les tailles de colonne dans le tableau ?
C'est un vrai tableau HTML et des div ?
Y'a aucune taille fixe si ?

**Comment by Thom-x** [comment]
Aucune taille fixe, il à l'air de s'optimiser pour tout afficher.
Dans le screen d'avant ça prend "pas mal" de place, mais les autres colonnes sont assez petites donc il fait la ligne la moins haute possible.

![capture](https://cloud.githubusercontent.com/assets/6797195/8747425/40ff2012-2c93-11e5-9544-8430d1665f67.PNG)
