### ISSUE TITLE
Popup de sélection de la langue est toujours en anglais

### ISSUE THREAD

**Issue by pguyard** [SII-Nantes/callForPaper#47]

**Comment by Thom-x** [comment]
Moi il est toujours en Anglais. On parle bien de ça ?

![capture](https://cloud.githubusercontent.com/assets/6797195/8808563/a4b5f1a0-2fe3-11e5-854e-ebe8882ac0a2.PNG)

**Comment by pguyard** [comment]
oui oui je dors ^^ c'est toujours en anglais ;)

**Comment by Thom-x** [comment]
Je corrige ça demain :p
