### ISSUE TITLE
[ADMIN] Ajout d'un bloc de contact du speaker

### ISSUE THREAD

**Issue by jefBinomed** [SII-Nantes/callForPaper#49]
ça serait pratique d'avoir un champ qui nous permette de joindre directement le speaker. En gros un truc similaire à notre champ de communication actuel mais cette fois ci à destination du speaker et qui envoie si possible des mails :)

**Comment by Thom-x** [comment]
Un formulaire pour envoyer un email au speaker ? Ou bien un fil de discussion ?

**Comment by jlandure** [comment]
Attention si on part là-dessus, il faut que quand le speaker répond à l'email (qu'il a reçu), cela s'ajoute dans le thread de message. C'est gérable normalement avec AppEngine mais c'est un dev assez conséquent !
Après on a deux façons de faire:
* soit on passe par des emails
  * côté admin, le fait d'ajouter un msg envoie un email
  * côté speaker, le fait de répondre envoie un email qui créé un msg
* soit on passe tout le temps par l'appli
  * côté admin, l'ajout d'un msg envoie un email au speaker en indiquant : "vous avez une nouvelle notif, allez ici pour la voir"
  * coté speaker, il doit tjs se connecter pour entrer un msg et cela envoie une notif aux admins du site.

**Comment by jlandure** [comment]
ajoute le tag [ADMIN] stp

**Comment by jefBinomed** [comment]
J'avais plus en tête un truc comme ta deuxième option : on passe tout le temps par l'appli et ça envoie juste un message au speaker disant qu'il a reçu un message :)

**Comment by jlandure** [comment]
ok pourquoi pas! c'est plus simple du coup car pas de retour d'email, juste un envoi de notifications :+1: 
@Thom-x à toi de voir si il y a des choses plus importantes
@Thom-x parait que tu refais l'appli en go ? t'as un repo que je regarde ? :p

**Comment by Thom-x** [comment]
Pour la discussion on garde les nom des différent Admins ou bien c'est seulement Admin (anonymisation des admins) ?

https://github.com/Thom-x/callForPaperGo, il date un peu avec toutes les issues ^^.

**Comment by jlandure** [comment]
Non on peut garder les noms des différents admins. Par contre, à nous côté orga de faire en sorte qu'il n'y ait pas 15 interlocuteurs différents ^^

@Thom-x faudra renommer en "goForPaper" pour que ce soit plus classe :)

**Comment by Thom-x** [comment]
@jlandure "goForPaper" ça change tout !

**Comment by Thom-x** [comment]
Quand la personne répond au message vous voulez être averti comment ?

- Email à tous les admins ?
- Email aux admins dans la conversation ? (voir règle du dessus si pas encore de conversation)
- Autre ?

Faut-il envoyer un message à d'autres admins quand un admin envoie lui même un message ?

**Comment by jefBinomed** [comment]
@jlandure on fait un mail à bureau  ? après comme tu disais, il est de notre charge de ne pas répondre tous mais au moins on serait tous au courant ?

**Comment by Thom-x** [comment]
Ok, j'avais pas pensé au bureau.

**Comment by jlandure** [comment]
Non il vaut mieux utiliser les emails indiqués pour les admins (appengine)... sinon l'appli est trop spécifique GDG Nantes :p
Bref, envoi au speaker et tous les admins en bcc ?

**Comment by jefBinomed** [comment]
ok ça me va :)

**Comment by Thom-x** [comment]
Et tous les admins quand une réponse du speaker ?

**Comment by jefBinomed** [comment]
ué

**Comment by Thom-x** [comment]
Petit détail, dans l'email il y a le lien de la session, mais les administrateurs ne peuvent pas y accéder puisque qu'il correspond au lien pour le speaker (dans son dashboard).
