### ISSUE TITLE
Le téléphone ne doit pas être une donnée obligatoire

### ISSUE THREAD

**Issue by jefBinomed** [SII-Nantes/callForPaper#5]

**Comment by Thom-x** [comment]
C'est déjà le cas, c'est surement a cause du "+33" qui apparaît tout seul quand on clique sur le champ, si on le supprime ça fonctionne.

**Comment by jefBinomed** [comment]
Tu peux pas faire en sorte que le +33 soit un prefix au champ du coup ?

Le jeu. 4 juin 2015 13:44, MAUGIN Thomas <notifications@github.com> a
écrit :

> C'est déjà le cas, c'est surement a cause du "+33" qui apparaît tout seul
> quand on clique sur le champ, si on le supprime ça fonctionne.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SII-Nantes/callForPaper/issues/5#issuecomment-108855809>
> .
>
-- 
-----------------------------------------------------------------------
Jean-François Garreau - Binomed - GDG Nantes
Tel : +336.48.28.15.28
Email perso: jean.francois.garreau@gmail.com
Email pro: jean.francois.garreau@binomed.fr
Site Web: http://jef.binomed.fr | http://gdgnantes.com
Follow me: @jefBinomed +JeanFrancoisGarreau
