### ISSUE TITLE
[ADMIN] Changer la catégorie d'un track

### ISSUE THREAD

**Issue by jefBinomed** [SII-Nantes/callForPaper#50]
ça serait pratique de pouvoir côté admin changer la catagorie d'un track. Des fois des speakers nous ont soumis des talks dans web alors que nous on le verrait plus dans mobile etc......

**Comment by jefBinomed** [comment]
à valider avec les autres par contre :p

**Comment by jlandure** [comment]
Pas d'accord :p
C'est à nous de demander au speaker s'il veut bien changer sa catégorie. C'est au speaker de toucher à son talk pas à nous.

**Comment by jefBinomed** [comment]
oui mais aujourd'hui l'édition n'est pas possible depuis le cfp :(

**Comment by jefBinomed** [comment]
car du coup, si on peut changer la catégorie, ça peut nous faciliter le travail au moment du verdict

**Comment by jlandure** [comment]
l'édition n'est pas possible ? ah oui on ne peut pas éditer un talk validé...
Faut p'etre prévoir un mini cycle de vie: brouillon -> validé -> brouillon etc...
bref à discuter avec les autres...

**Comment by jefBinomed** [comment]
Bah en fait c'est pour ça que je me dis un truc facile de ce côté là, c'est de : 
1. Avoir les échanges avec les speakers pour éventuellement compléter (certes dans les commentaires) le talk
2. Nous juste pouvoir éditer l'information de catégorie car pour trier au moment du résultat ça sera plus simple. 

Je me dis que mettre un système passage en brouillon et en validé pourra faire en sorte que certains oublient leurs talks ?

**Comment by jlandure** [comment]
oui ok pour ne pas pouvoir rééditer un truc validé...

**Comment by jefBinomed** [comment]
Après, on va demander l'avis du public :)

@Thom-x attends notre retour :)

**Comment by jefBinomed** [comment]
Bon les gens sont ok pour l'édition depuis le mode admin. Pas de cycle de vie en perspective

**Comment by jlandure** [comment]
Quelques questions: on a un log des changements effectués ? on peut changer uniquement le track ou autre chose ?
Genre `jef a changé la catégorie de 'découverte' à 'mobile' le XX` ?
Peut-être qu'on peut mettre ça automatiquement en commentaire ?

**Comment by Thom-x** [comment]
On peut changer seulement la track. Je peux ajouter un log dans les commentaires si vous voulez.
