### ISSUE TITLE
[ADMIN] Scrollbar horizontale apparue

### ISSUE THREAD

**Issue by jlandure** [SII-Nantes/callForPaper#52]
Sur la page "tableau", j'ai un scrollbar horizontal assez moche :)
![scrollbar_horizontal](https://cloud.githubusercontent.com/assets/525974/8935319/5ed208fe-354c-11e5-92ae-9fa08b4b9ce9.png)

**Comment by Thom-x** [comment]
Ouais, et le tableau est très moche (ça dépasse).
