### ISSUE TITLE
Ajout d'une fonction d'export csv dans la partie admin

### ISSUE THREAD

**Issue by jefBinomed** [SII-Nantes/callForPaper#54]
Afin de pouvoir traiter au mieux les conférences à la fin (à défaut de coder une partie admin / planification), serait-il possible de créer un bête export csv des données du cfp afin de faire ressortir les notes / rejets / coups de coeurs.

J'aurais bien vu un truc du genre : 
 * Type de conf
 * Track
 * Nom de la conf
 * Nom du speaker
 * Difficulté
 * Note finale
 * Nombre Coups de coeurs
 * Nombre Rejets
 * Vote de chacun de nous (genre une colonne vote JF / vote Julien / ....)

**Comment by jlandure** [comment]
On fera une requête jef car rien en export correspondra à ce que l'on
souhaite parfaitement. Je suis plutôt contre.
Pour info, les talks + desc + speaker sont déjà dans un spreadsheet.
Le jour j, je ferai ça lors de notre soirée "délibération".

**Comment by jefBinomed** [comment]
Je sais qu'on a les infos principales (speaker / desc /...) mais il manque la note :( c'est quand même chiant de ce dire que manuellement, on va devoir remplir quelque part, la note de chacun des votes alors qu'un ptit export csv, ça peut faire le job facilement

**Comment by jlandure** [comment]
Mais je le ferai l'export avec une req du datastore si on en a besoin...

**Comment by jefBinomed** [comment]
ça me va dans ce cas là :)
