### ISSUE TITLE
Il faut pouvoir fermer le CFP

### ISSUE THREAD

**Issue by jefBinomed** [SII-Nantes/callForPaper#55]
Il faut qu'on puisse fermer le CFP aux nouvelles soumissions / validations de talks. Car comme on a une date butoire, on va pas non plus couper le serveur :)

**Comment by Thom-x** [comment]
/ ! \ Une fois le merge fait il faut activer la soumission (désactivée par défaut)
![capture](https://cloud.githubusercontent.com/assets/6797195/9424818/b9a40a72-48fa-11e5-8d8e-b177a6e1111c.PNG)

**Comment by xavmarc** [comment]
Quand le CFP <b>est fermé</b>, l'icône d'édition reste présent sur les brouillons, il faudrait ne plus l'afficher. 
Par contre tu peux laisser l'icône de suppression.
