### ISSUE TITLE
Ajouter la date de fin du CFP dès la page d'accueil.

### ISSUE THREAD

**Issue by jlandure** [SII-Nantes/callForPaper#56]
Beaucoup de monde me demande la date de fin et c'est vrai qu'elle n'est pas indiquée 'clairement'.
Je proposerai bien de l'indiquer dans le bandeau soit au milieu soit à droite: "ouvert jusqu'au 31/08 23h59" | Se connecter | Français.

J'indiquerai bien aussi le nombre de talks déjà déposé pour mettre la pression au speaker. :dancer:

**Comment by Thom-x** [comment]
>c'est vrai qu'elle n'est pas indiquée 'clairement'.

Elle n'est pas indiquée du tout donc c'est normal ^^

>J'indiquerai bien aussi le nombre de talks déjà déposé pour mettre la pression au speaker. :dancer:

OK

**Comment by xavmarc** [comment]
Pour le nombre de talks déjà déposé on peut le mettre a droite du bouton "Créer un nouveau talk"

**Comment by Thom-x** [comment]
Je l'ai mis à gauche T_T

**Comment by xavmarc** [comment]
Mettre "Ouvert jusqu'au 31/08/2015" plutôt que "Ouvert jusqu'au 01/09/2015"

**Comment by Thom-x** [comment]
Dans ce cas il faut modifier le fichier `src/main/webapp/WEB-INF/application-dev.properties` :

    app.releasedate=01/09/2015

A faire directement sur le repo du GDG Nantes puisque c'est une conf.

**Comment by jlandure** [comment]
On veut aussi une date de délibération
...au pire je mettrai en dur pour le GDG ^^

**Comment by Thom-x** [comment]
Ah... J'ai regardé juste le début de la phrase...
Je peux rajouter c'est seulement dans le JS.
