### ISSUE TITLE
On a pas de séparation de profil avec la soumission de talk

### ISSUE THREAD

**Issue by jefBinomed** [SII-Nantes/callForPaper#6]
ça serait plus pertinant d'avoir d'un côté, l'édition du profil et de l'autre la soumission de talk.

à chaque fois qu'on soumet un talk, on est obligé de re soumettre son profil

**Comment by Thom-x** [comment]
Et si on a un profil et quand on créer un nouveau talk les champs sont automatiquement remplis ça peut être mieux non ?

**Comment by jefBinomed** [comment]
Oui en effet et sinon tu peux aussi du coup préremplir direct l'email ?

Le jeu. 4 juin 2015 à 16:09, MAUGIN Thomas <notifications@github.com> a
écrit :

> Et si on a un profil et quand on créer un nouveau talk les champs sont
> automatiquement remplis ça peut être mieux non ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SII-Nantes/callForPaper/issues/6#issuecomment-108909769>
> .
>
-- 
-----------------------------------------------------------------------
Jean-François Garreau - Binomed - GDG Nantes
Tel : +336.48.28.15.28
Email perso: jean.francois.garreau@gmail.com
Email pro: jean.francois.garreau@binomed.fr
Site Web: http://jef.binomed.fr | http://gdgnantes.com
Follow me: @jefBinomed +JeanFrancoisGarreau
